### ISSUE TITLE
Floating point exception on startup

### ISSUE THREAD

**Issue by mehturt** [rbrito/xpdf-poppler#5] opened 2010-06-11 07:45 UTC
I am getting SIGFPE upon startup, the gdb backtrace is:

Program received signal SIGFPE, Arithmetic exception.
0x00007ffff7b47131 in SplashScreen::buildDispersedMatrix(int, int, int, int, int) () from /usr/lib/libpoppler.so.5
(gdb) bt
#0  0x00007ffff7b47131 in SplashScreen::buildDispersedMatrix(int, int, int, int, int) () from /usr/lib/libpoppler.so.5
#1  0x00007ffff7b47d58 in SplashScreen::SplashScreen(SplashScreenParams*) () from /usr/lib/libpoppler.so.5
#2  0x00007ffff7b485fa in SplashState::SplashState(int, int, int, SplashScreenParams*) () from /usr/lib/libpoppler.so.5
#3  0x00007ffff7b3619d in Splash::Splash(SplashBitmap_, int, SplashScreenParams_) () from /usr/lib/libpoppler.so.5
#4  0x00007ffff7a653a5 in SplashOutputDev::SplashOutputDev(SplashColorMode, int, int, unsigned char*, int, int) () from /usr/lib/libpoppler.so.5
#5  0x000000000040b88a in CoreOutputDev::CoreOutputDev(SplashColorMode, int, int, unsigned char_, int, void (_)(void_, int, int, int, int, int), void_) ()
#6  0x0000000000415b05 in PDFCore::PDFCore(SplashColorMode, int, int, unsigned char*, int) ()
#7  0x000000000041b0fc in XPDFCore::XPDFCore(_WidgetRec_, _WidgetRec_, unsigned char*, unsigned long, unsigned long, int, int, int, int) ()
#8  0x0000000000421280 in XPDFViewer::initCore(_WidgetRec*, int) ()
#9  0x0000000000422402 in XPDFViewer::initWindow(int) ()
#10 0x0000000000423d6f in XPDFViewer::XPDFViewer(XPDFApp_, GooString_, int, GooString_, int, GooString_, GooString*) ()
#11 0x00000000004176ba in XPDFApp::open(GooString_, int, GooString_, GooString*) ()
#12 0x0000000000424a69 in main ()

I am using Ubuntu 10.04 on x86_64, libpoppler5 0.12.4-0ubuntu5.

**Comment by khaledhosny** [comment] 2010-06-11 09:36
I have the same issue on Ubuntu 9.10, x86, libpoppler5 0.12.0-0ubuntu2.2.

**Comment by rbrito** [comment] 2010-06-16 18:54
Hummm, for some reason that I don't know, I did not receive a notification for your e-mail, Khaled.

Anyway, I will set up an ubuntu system here to see what is going on, but there are some strange things regarding poppler, as I don't see any of the behaviour that you both mentioned.

I guess that I will _have_ see if the problem is in the xpdf code or in poppler.

Thanks for your confirmation of Mehturt's report.

**Comment by rbrito** [comment] 2010-06-17 16:17
Just for the record, I _was_ able to reproduce the error in an Ubuntu system and I discovered that the bug is a problem in a recursion in poppler itself.

I filed a bug with ubuntu at https://bugs.launchpad.net/ubuntu/+source/poppler/+bug/595568.

Thanks for both of your reports, Rogério Brito.

**Comment by rbrito** [comment] 2010-10-27 11:59
Is this issue still being seen? I think that we can close this, right?

Thanks, Rogério Brito.

**Comment by mehturt** [comment] 2010-10-27 12:01
Yes, go ahead.

**Comment by rbrito** [comment] 2010-10-27 12:04
Thank you very much.

BTW, feel free too take a look at the next few revisions of xpdf-poppler. It will start to have some new features.

Regards.

**Closed as completed** 2010-10-27 18:59 UTC
